### ISSUE TITLE
Adding node version to array when using strategy.matrix

### ISSUE THREAD

**Issue by oscard0m** [gr2m/octoherd-script-bump-node-version-in-workflows#2]
Would this be something interesting to cover or is too specific?

example:
```yaml
jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["12", "14", "16"]
```

https://github.com/octokit/octokit.js/blob/main/.github/workflows/test.yml
